[feat] 유저 - 문의 등록하기 API
40LF0/couple_project_backend pull request #20
Opened 2024-01-20 02:08 UTC by sunnism03

1. [유저] 문의 등록
2. [유저] 내가 한 문의 조회 -> pagable
3. [관리자] 답변 대기 중인 문의 조회 -> pagable
4. [관리자] 답변 등록

2024-01-20 04:43 UTC, 40LF0 requested changes
문의 객체 생성할 때, member id관련 로직이 빠진 것 같습니다.

2024-01-20 04:43 UTC, 40LF0 commented on src/main/java/com/example/spring/domain/qna/QnaService.java
> +        Qna qna = QnaConverter.toQnaEntity(request);
converter에서 문의 제목과 문의 내용을 entity로 바꾸는 것을 확인하였습니다. 하지만, 멤버 아이디에 관한 로직은 확인하지 못하였습니다.

2024-01-20 12:54 UTC, sunnism03 commented on src/main/java/com/example/spring/domain/qna/QnaService.java
> +        Qna qna = QnaConverter.toQnaEntity(request);
확인했습니다. Converter에 멤버 아이디 로직 추가했습니다!

2024-01-21 02:49 UTC, 40LF0 commented on src/main/java/com/example/spring/domain/qna/QnaService.java
> +        Qna qna = QnaConverter.toQnaEntity(request);
해당 부분 commit 해주시겠어요?

2024-01-24 11:01 UTC, 40LF0 reviewed
QnaConverter 클래스를 Spring Bean으로 등록 제안

2024-01-24 11:01 UTC, 40LF0 commented on src/main/java/com/example/spring/domain/qna/QnaConverter.java
> +    public static Qna toQnaEntity(QnaRequestDTO.QnaSaveDto request){
다른 컴포넌트인 memberService를 이용함으로, QnaConverter 또한 컴포넌트로 등록하는 것이 좋아 보입니다.
![image](https://github.com/40LF0/couple_project_backend/assets/96645965/d5b18a64-330c-44f6-875f-efa550f33726)
![image](https://github.com/40LF0/couple_project_backend/assets/96645965/8499e085-9e50-41ee-9863-baf9ad9da85f)

2024-01-24 17:25 UTC, sunnism03 commented on src/main/java/com/example/spring/domain/qna/QnaConverter.java
> +    public static Qna toQnaEntity(QnaRequestDTO.QnaSaveDto request){
네 추가하겠습니다!

2024-01-28 06:33 UTC, 40LF0 approved these changes

2024-02-06 05:33 UTC, merged